cflags-y			+= -os
obj-$(CONFIG_MSM_HOTPLUG)	+= msm_hotplug.o
obj-$(CONFIG_AUTOSMP)		+= autosmp.o
obj-$(CONFIG_INTELLI_HOTPLUG)		+= intelli_hotplug.o
obj-$(CONFIG_BRICKED_HOTPLUG) += bricked_hotplug.o
